/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vaccineui;

import vaccineui.Dashboard1;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import vaccineui.MYCONNECTION;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.event.*;
import javax.swing.DefaultListModel;
import javax.swing.UIManager;
import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import com.toedter.calendar.JDateChooser;





/**
 *
 * @author  soham lohote
 */
public class Dashboard1 extends javax.swing.JFrame {
     private DefaultListModel<String> listModel;
     
    /**
     * Creates new form Dashboard1
     */
    public Dashboard1() {
        initComponents();
        listModel = new DefaultListModel<>();
        PList.setModel(listModel);
        
        /**String username1= username;
        ResultSet rs = null; // Declare rs here

         //String username = jTextField1.getText(); 
       

        String query = "SELECT name,dob,aadhaarno, address, pincode, username , email, mobileno FROM signup WHERE username =? ";

        try (Connection conn = MYCONNECTION.getConnection();
             PreparedStatement ps = conn.prepareStatement(query)) { // Renamed ps to ps1

            ps.setString(1, username1);
           rs = ps.executeQuery(); // Use the already declared rs

            if (rs.next()) {
                String name = rs.getString("name");
                String dob = rs.getString("dob");
                String aadhaarno = rs.getString("aadhaarno");
                String address = rs.getString("address");
                String pincode = rs.getString("pincode");
                String username2 = rs.getString("username");
                String email = rs.getString("email");
                String mobileno = rs.getString("mobileno");
                
                //String retrievedUsername = rs.getString("username");
                
                tf1.setText(name);
                tf3.setText(dob);
                tf4.setText(aadhaarno);
                add.setText(address);
                tf5.setText(pincode);
                tf6.setText(username2);
                tf7.setText(email);
                tf8.setText(mobileno);
            } else {
                JOptionPane.showMessageDialog(null, "Username not found ");
            }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage());
        } finally {
            // Close the ResultSet in the finally block
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }*/
        //this.username=username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel18 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PList = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        view = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        adate = new com.toedter.calendar.JDateChooser();
        jLabel33 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        resultLabel1 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DASHBOARD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 350, 70));

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 110));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jButton5.setBackground(new java.awt.Color(102, 0, 0));
        jButton5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information-system.png"))); // NOI18N
        jButton5.setText("PERSONAL INFORMATION");
        jButton5.setIconTextGap(10);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 0, 0));
        jButton6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vaccine.png"))); // NOI18N
        jButton6.setText("BOOK VACCINE");
        jButton6.setIconTextGap(10);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 230, 490));

        jPanel7.setBackground(new java.awt.Color(102, 0, 0));
        jPanel7.setAutoscrolls(true);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information-system.png"))); // NOI18N
        jLabel1.setText("PERSONAL INFORMATION");
        jLabel1.setIconTextGap(20);
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 320, 40));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("NAME:");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 60, 30));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("AADHAAR NUMBER:");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, 30));

        jLabel16.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DATE OF BIRTH:");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, 30));

        jLabel20.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("PINCODE:");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, 30));

        jLabel21.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("RESIDENTIAL ADDRESS:");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 160, 30));

        jLabel22.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("MOBILE NO:");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 110, 30));

        jLabel23.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("EMAIL ID:");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 100, 30));

        labelno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelno.setForeground(new java.awt.Color(255, 255, 255));
        labelno.setText("jLabel3");
        jPanel7.add(labelno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 130, -1));

        labelemail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelemail.setForeground(new java.awt.Color(255, 255, 255));
        labelemail.setText("jLabel3");
        jPanel7.add(labelemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 260, -1));

        labeladd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labeladd.setForeground(new java.awt.Color(255, 255, 255));
        labeladd.setText("jLabel3");
        jPanel7.add(labeladd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 220, 60));

        labeladhar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labeladhar.setForeground(new java.awt.Color(255, 255, 255));
        labeladhar.setText("jLabel3");
        jPanel7.add(labeladhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 150, -1));

        labeldob.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labeldob.setForeground(new java.awt.Color(255, 255, 255));
        labeldob.setText("jLabel3");
        jPanel7.add(labeldob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 280, -1));

        labelpin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelpin.setForeground(new java.awt.Color(255, 255, 255));
        labelpin.setText("jLabel3");
        jPanel7.add(labelpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 100, -1));

        labelname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelname.setForeground(new java.awt.Color(255, 255, 255));
        labelname.setText("jLabel3");
        jPanel7.add(labelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 180, -1));

        PList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PList.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        PList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Profile 1", "Profile 2", "Profile 3", "Profile 4", "Profile 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        PList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        PList.setToolTipText("");
        PList.setSelectionBackground(new java.awt.Color(102, 0, 0));
        PList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        PList.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                PListComponentAdded(evt);
            }
        });
        PList.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                PListPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(PList);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 190, 180));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Your Profiles");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 120, 30));

        view.setBackground(new java.awt.Color(153, 0, 0));
        view.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("LOAD PROFILES");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel7.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 190, 30));

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ADD PROFILE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 190, 30));

        jButton7.setBackground(new java.awt.Color(153, 0, 0));
        jButton7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("DELETE PROFILE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 190, 30));

        labeluser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labeluser.setForeground(new java.awt.Color(255, 255, 255));
        labeluser.setText("jLabel3");
        jPanel7.add(labeluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 140, -1));

        jLabel18.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Welcome");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, 30));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel18);

        jPanel22.setBackground(new java.awt.Color(102, 0, 0));
        jPanel22.setAutoscrolls(true);
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vaccine.png"))); // NOI18N
        jLabel2.setText("BOOK VACCINE");
        jLabel2.setIconTextGap(20);
        jPanel22.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 320, 40));

        jButton9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 0, 51));
        jButton9.setText("CHECK AVAILBLITY");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel22.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 200, 40));

        jLabel32.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("SELECT VACCINE:");
        jPanel22.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 40));

        jComboBox1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Covishield", "Covaccine", "Polio", "HEP B", "BCG" }));
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });
        jPanel22.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 170, 30));
        jPanel22.add(adate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 170, 30));

        jLabel33.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("SELECT PROFILE:");
        jPanel22.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, 30));

        jButton10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(204, 0, 51));
        jButton10.setText("BOOK APOINTMENT");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel22.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 200, 40));

        resultLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        resultLabel1.setForeground(new java.awt.Color(255, 255, 255));
        resultLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel22.add(resultLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 630, 80));

        jLabel34.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("DATE OF VACCINATION: ");
        jPanel22.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, 30));

        jComboBox2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jPanel22.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 170, 30));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("tab2", jPanel19);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 720, 530));

        setSize(new java.awt.Dimension(959, 609));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover3ActionPerformed

    private void rSButtonHover4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover4ActionPerformed

    private void aboutusComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_aboutusComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutusComponentShown

    private void aboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutusActionPerformed

    private void checkstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkstatusActionPerformed

    private void downloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downloadActionPerformed

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    private void rSButtonHover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover2ActionPerformed

    private void txtpincodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpincodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpincodeActionPerformed

    private void txtpincode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpincode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpincode1ActionPerformed

    private void txtpincode4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpincode4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpincode4ActionPerformed

    private void rSPasswordTextPlaceHolder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSPasswordTextPlaceHolder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSPasswordTextPlaceHolder1ActionPerformed

    private void txtpincode5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpincode5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpincode5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jComboBox2.removeAllItems();
        String u=labeluser.getText();
        ResultSet rs = null;
        String query = "SELECT member_name FROM profiles WHERE main_username =?";
        try (Connection conn = MYCONNECTION.getConnection();
            PreparedStatement ps = conn.prepareStatement(query)) { // Use PreparedStatement correctly
            
            ps.setString(1,u); // Set the pin

            rs = ps.executeQuery(); // Execute query

            // Clear the existing data in the model
            

            while (rs.next()) {
                String data = rs.getString("member_name");
                jComboBox2.addItem(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } 
       jButton10.setEnabled(false);
        UIManager.put("Button.disabledText", Color.WHITE);  // Text color for disabled buttons
        UIManager.put("Button.disabledBackground", Color.LIGHT_GRAY);
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        homepage1 b = new homepage1();
        b.show();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String selectvaccine= (String) jComboBox1.getSelectedItem();
        try (Connection conn = MYCONNECTION.getConnection();
             Statement stmt = conn.createStatement()) {
             
            String sql = "SELECT quantity FROM Vaccines WHERE vaccine_name = '" + selectvaccine + "'";
            ResultSet rs = stmt.executeQuery(sql);
            
            if (rs.next()) {
                int quantity = rs.getInt("quantity");
                if (quantity > 0) {
                    resultLabel1.setText(selectvaccine + " is available. You can Book a apointment");
                    jButton10.setEnabled(true);
                } else {
                    resultLabel1.setText(selectvaccine + " is not available.");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed
    public int updatelist(){
        String u=labeluser.getText();
        ResultSet rs = null;
       // String user =  // Get the pin from text field
        List<String> dataList = new ArrayList<>();
         

        
        String query = "SELECT member_name FROM profiles WHERE main_username =?";
        try (Connection conn = MYCONNECTION.getConnection();
            PreparedStatement ps = conn.prepareStatement(query)) { // Use PreparedStatement correctly
            
            ps.setString(1,u); // Set the pin

            rs = ps.executeQuery(); // Execute query

            // Clear the existing data in the model
            listModel.clear();

            while (rs.next()) {
                String data = rs.getString("member_name");
                jComboBox2.addItem(data);
                // Fetch the data
                dataList.add(data);

            }
            if (dataList.isEmpty()) {
               
                return 1;// Print message if no results
            } else {
                   
                for (String item : dataList) {
                    listModel.addElement(item); // Add each item to the JList model
                }
                return 0;
            }

        } catch (Exception e) {
            e.printStackTrace();
        } 
       return 0;
    }
    private static boolean isUsernameExists(String username) {
        String query = "SELECT COUNT(*) FROM VaccineRecords WHERE m_name = ?";
        try (PreparedStatement ps = MYCONNECTION.getConnection().prepareStatement(query)) {
            ps.setString(1, username);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                return rs.getInt(1) > 0; // Returns true if username exists
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage());
        }
        return false; // Returns false if no error or username does not exist
    }
    public boolean isAppointmentDateValid(JDateChooser dateChooser) {
    // Get the selected date (Appointment Date) from the JDateChooser
    Date appointmentDate = dateChooser.getDate();
    
    // Check if no date is selected
    if (appointmentDate == null) {
        JOptionPane.showMessageDialog(null, "Please select an appointment date.");
        return false; 
    }

    // Get tomorrow's date
    Calendar tomorrow = Calendar.getInstance();
    tomorrow.add(Calendar.DAY_OF_MONTH, 1); // Add one day to today

    // Get the date one month from tomorrow
    Calendar nextMonth = Calendar.getInstance();
    nextMonth.add(Calendar.MONTH, 1); // Add one month to today

    // Set the time to the start of the day for comparison
    tomorrow.set(Calendar.HOUR_OF_DAY, 0);
    tomorrow.set(Calendar.MINUTE, 0);
    tomorrow.set(Calendar.SECOND, 0);
    tomorrow.set(Calendar.MILLISECOND, 0);

    // Set the time to the end of the day for next month
    nextMonth.set(Calendar.HOUR_OF_DAY, 23);
    nextMonth.set(Calendar.MINUTE, 59);
    nextMonth.set(Calendar.SECOND, 59);
    nextMonth.set(Calendar.MILLISECOND, 999);
    
    // Check if the selected appointment date is within the valid range
    if (appointmentDate.before(tomorrow.getTime())) {
        // If the date is before tomorrow
        JOptionPane.showMessageDialog(null, "The appointment date must be tomorrow or later.");
        return false;
    } else if (appointmentDate.after(nextMonth.getTime())) {
        // If the date is after one month from tomorrow
        JOptionPane.showMessageDialog(null, "The appointment date must be within the next month.");
        return false;
    }
    
    // If the date is valid (within tomorrow to next month), return true
    return true;
}
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
                 String name= labeluser.getText();
                 String selectvaccine= (String) jComboBox1.getSelectedItem();
                 String selectprofile= (String) jComboBox2.getSelectedItem();
                 
                  if(isAppointmentDateValid(adate)){
                SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-yyyy");
                 String date = dateformat.format(adate.getDate());
            if (isUsernameExists(selectprofile)) {
                        JOptionPane.showMessageDialog(null, "YOU already have a apointment.");
                    }else{
                 String memberIdQuery = "SELECT member_id FROM profiles WHERE member_name = ?";
                 String query = "INSERT INTO `vaccinerecords`(`member_id`,`m_name`,`vaccine_name`, `appointment_date`,`username`) VALUES (?,?,?,?,?)";
                 PreparedStatement ps1;

        try {
            ps1 = MYCONNECTION.getConnection().prepareStatement(memberIdQuery);
            ps1.setString(1, selectprofile);
            ResultSet rs = ps1.executeQuery();

        if (rs.next()) {
            // If a member is found, get the member ID
            int memberId = rs.getInt("member_id");
            PreparedStatement ps2;
            ps2 = MYCONNECTION.getConnection().prepareStatement(query);
            ps2.setInt(1, memberId);
            ps2.setString(2, selectprofile);
            ps2.setString(3, selectvaccine);
            ps2.setString(4, date);
            ps2.setString(5, name);



            if(ps2.executeUpdate() > 0) {
        JOptionPane.showMessageDialog(null, "Apointment Booked");
        resultLabel1.setText("Visit the Vaccination center on "+date);
        
       }
        }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage());
        } 
                 }
                  }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        int bol=updatelist();   
        if(bol==1)
 JOptionPane.showMessageDialog(null, "No Profile Added ");// TODO add your handling code here:
    }//GEN-LAST:event_viewActionPerformed
public boolean hasFiveEntries(String username) {
        String countSQL = "SELECT COUNT(*) AS entry_count FROM profiles WHERE main_username = ?";

        try (PreparedStatement pstmt = MYCONNECTION.getConnection().prepareStatement(countSQL)) {
             
            // Set the parameter for the prepared statement
            pstmt.setString(1, username);
            
            // Execute the query
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                int entryCount = rs.getInt("entry_count");
                return entryCount >= 5; // Return true if there are 5 or more entries
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        return false; // Return false if an error occurs or no entries found
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if (hasFiveEntries(labeluser.getText())) {
            JOptionPane.showMessageDialog(null, "Max 5 Profile!!");           
        } else {
           newProfile p= new newProfile();
           p.setLocationRelativeTo(null);
        p.show();  
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void PListComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_PListComponentAdded
       // updatelist();            // TODO add your handling code here:
    }//GEN-LAST:event_PListComponentAdded

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String selectedValue = PList.getSelectedValue();
        if(PList.getSelectedValue() == null){
            JOptionPane.showMessageDialog(null, "Select Profile to delete first");
            return;
        }else{
            String query = "DELETE FROM profiles WHERE member_name = ?";

        try
             (PreparedStatement ps = MYCONNECTION.getConnection().prepareStatement(query)) {
             
            // Set the parameter for the prepared statement
            ps.setString(1, selectedValue);
            
            // Execute the delete operation
             if(ps.executeUpdate() > 0) {
        JOptionPane.showMessageDialog(null, "Profile deleted");
        updatelist();
        
        
       }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage());
        } 
                 }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void PListPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_PListPropertyChange
       // updatelist();        // TODO add your handling code here:
    }//GEN-LAST:event_PListPropertyChange

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
            jButton10.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard1().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JList<String> PList;
    private com.toedter.calendar.JDateChooser adate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    public static final javax.swing.JLabel labeladd = new javax.swing.JLabel();
    public static final javax.swing.JLabel labeladhar = new javax.swing.JLabel();
    public static final javax.swing.JLabel labeldob = new javax.swing.JLabel();
    public static final javax.swing.JLabel labelemail = new javax.swing.JLabel();
    public static final javax.swing.JLabel labelname = new javax.swing.JLabel();
    public static final javax.swing.JLabel labelno = new javax.swing.JLabel();
    public static final javax.swing.JLabel labelpin = new javax.swing.JLabel();
    public static final javax.swing.JLabel labeluser = new javax.swing.JLabel();
    private javax.swing.JLabel resultLabel1;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
